# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "sandbox-tf-state-us-west-2"
    key            = "terragrunt-aws-template/deployments/sandbox/us-west-2/helloworld/terraform.tfstate"
    region         = "us-west-2"
    dynamodb_table = "terraform-state-lock"
    encrypt        = true
    assume_role = {
      role_arn = "arn:aws:iam::965345602646:role/Org/CodeDeployRole"
    }
  }
}
