# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
# local.aws_account_name: sandbox
# local.aws_account_id: 965345602646
# local.aws_region: us-west-2
# local.deployment_name: helloworld

provider "aws" {
  region = "us-west-2"

  assume_role {
    role_arn = "arn:aws:iam::965345602646:role/Org/CodeDeployRole"
  }

  default_tags {
    tags = {
      "Repo"            = "terragrunt-aws-template"
      "terraform:state" = "s3://sandbox-tf-state-us-west-2/terragrunt-aws-template/deployments/sandbox/us-west-2/helloworld/terraform.tfstate"
    }
  }
}
