---
name: terragrunt

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - '*'
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

env:
  working_dir: 'deployments'
  TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    container:
      image: hansohn/terraform-aws:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check terragrunt HCL
        run: 'terragrunt hclfmt --terragrunt-check --terragrunt-diff'

  # validate:
  #   name: Validate
  #   runs-on: ubuntu-latest
  #   container: hansohn/terrafrom-aws:latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Create Terraform Plugin Cache Dir
  #       run: mkdir -p $TF_PLUGIN_CACHE_DIR

  #     - name: Terraform Plugin Cache
  #       uses: actions/cache@v4.0.1
  #       with:
  #         path: ${{ env.TF_PLUGIN_CACHE_DIR }}
  #         key: ${{ runner.os }}-terraform-plugin-cache-${{ hashFiles('**/.terraform.lock.hcl') }}

  #     - name: Validate
  #       run: 'terragrunt run-all validate --backend=false'

  # plan:
  #   name: Plan
  #   runs-on: ubuntu-latest
  #   container: hansohn/terrafrom-aws:latest
  #   needs: [ validate ]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Create Terraform Plugin Cache Dir
  #       run: mkdir -p $TF_PLUGIN_CACHE_DIR

  #     - name: Terraform Plugin Cache
  #       uses: actions/cache@v4.0.1
  #       with:
  #         path: ${{ env.TF_PLUGIN_CACHE_DIR }}
  #         key: ${{ runner.os }}-terraform-plugin-cache-${{ hashFiles('**/.terraform.lock.hcl') }}

  #     - name: Plan
  #       run: 'terragrunt run-all plan'

  # deploy:
  #   name: Deploy
  #   runs-on: ubuntu-latest
  #   container: hansohn/terrafrom-aws:latest
  #   needs: [ plan ]
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@main

  #     - name: Create Terraform Plugin Cache Dir
  #       run: mkdir -p $TF_PLUGIN_CACHE_DIR

  #     - name: Terraform Plugin Cache
  #       uses: actions/cache@v4.0.1
  #       with:
  #         path: ${{ env.TF_PLUGIN_CACHE_DIR }}
  #         key: ${{ runner.os }}-terraform-plugin-cache-${{ hashFiles('**/.terraform.lock.hcl') }}

  #     - name: Deploy
  #       run: 'terragrunt run-all apply'

  slack:
    name: Slack
    runs-on: ubuntu-latest
    needs: [ format ]
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Slack Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          channel: ${{ secrets.SLACK_CHANNEL_ID }}
          name: ${{ secrets.SLACK_USERNAME }}
          icon_url: "https://cdn-icons-png.flaticon.com/512/25/25231.png"
